# Assignment: Orthogonal Matrices

## Name: Sabahat Yaqoob
## Roll number: 362840


### Create an orthogonal matrix Q. Show that Q*transpose(Q) = I. Show that Q*inverse(Q) = I.

In [5]:
import numpy as np
Q= np.matrix([[0, -1, 0],[1, 0, 0],[0, 0, -1]])
Q_transpose= Q.transpose()
A1= np.dot(Q_transpose,Q)
print(A1)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [6]:
Q_inverse= np.linalg.inv(Q)
A2= np.dot(Q_inverse,Q)
print(A2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
